2023-03-23 17:17:47,166 INFO: Microblog startup [in /home/kelvintrc/Desktop/IdeaPool/app/__init__.py:44]
2023-03-23 17:46:19,657 INFO: Microblog startup [in /home/kelvintrc/Desktop/IdeaPool/app/__init__.py:46]
2023-03-23 17:46:43,528 ERROR: Exception on /reset_password_request [POST] [in /home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kelvintrc/Desktop/IdeaPool/app/routes.py", line 186, in reset_password_request
    send_password_reset_email(user)
  File "/home/kelvintrc/Desktop/IdeaPool/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/kelvintrc/Desktop/IdeaPool/app/email.py", line 30, in send_email
    Thread(target=send_async_email, args=(app, msg)).start()
NameError: name 'Thread' is not defined
2023-03-23 17:49:00,937 ERROR: Exception on /reset_password_request [POST] [in /home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kelvintrc/Desktop/IdeaPool/app/routes.py", line 186, in reset_password_request
    send_password_reset_email(user)
  File "/home/kelvintrc/Desktop/IdeaPool/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/kelvintrc/Desktop/IdeaPool/app/email.py", line 30, in send_email
    Thread(target=send_async_email, args=(app, msg)).start()
NameError: name 'Thread' is not defined
2023-03-23 18:05:03,148 INFO: Microblog startup [in /home/kelvintrc/Desktop/IdeaPool/app/__init__.py:48]
2023-03-23 18:11:08,178 INFO: Microblog startup [in /home/kelvintrc/Desktop/IdeaPool/app/__init__.py:48]
2023-03-23 18:18:55,393 INFO: Microblog startup [in /home/kelvintrc/Desktop/IdeaPool/app/__init__.py:48]
2023-03-23 18:19:50,848 ERROR: Exception on /reset_password_request [POST] [in /home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kelvintrc/Desktop/IdeaPool/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kelvintrc/Desktop/IdeaPool/app/routes.py", line 186, in reset_password_request
    send_password_reset_email(user)
  File "/home/kelvintrc/Desktop/IdeaPool/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/kelvintrc/Desktop/IdeaPool/app/email.py", line 30, in send_email
    Thread(target=send_async_email, args=(app, msg)).start()
NameError: name 'Thread' is not defined
2023-03-24 20:25:06,971 INFO: Microblog startup [in /home/kelvintrc/Desktop/IdeaPool/app/__init__.py:48]
2023-03-24 20:36:39,310 INFO: Microblog startup [in /home/kelvintrc/Desktop/IdeaPool/app/__init__.py:50]
